### ISSUE TITLE
windows10 使用导出uniapp 无效

### ISSUE THREAD

**Issue by JavaToNull** [ezshine/wxapkg-convertor#1]
windows10 使用导出功能失败 ， 可以看下么

**Comment by ezshine** [comment]
我在win10上试过，没问题的。需要注意，必须从手机android模拟器里获取wxapkg..你先拿这个仓库里的wxapkg试验。

**Comment by yuanjianhua** [comment]
wind10 可以导出uniapp?

**Comment by yuanjianhua** [comment]
@ezshine

**Comment by ezshine** [comment]
@yuanjianhua  可以，我试过的。

**Comment by yuanjianhua** [comment]
> @yuanjianhua 可以，我试过的。

您是在虚拟机中还是直接导出呢

**Comment by ezshine** [comment]
@yuanjianhua 我是用的virtualbox虚拟的win10系统，要不你加我qq：7473635，把你拿到的wxapkg发我。

**Comment by ezshine** [comment]
新版已经去掉了直接转uniapp而是跳转到转uniapp的仓库，taro也是如此。
