### ISSUE TITLE
打包可以添加 --asar，减少文件碎片 

### ISSUE THREAD

**Issue by mqycn** [ezshine/wxapkg-convertor#5]
添加 --asar 参数后，打包后只有73个文件
现在的版本，打包后 有38090个文件，下载后解压速度非常慢

https://github.com/ezshine/wxapkg-convertor/blob/083ee496f5e9850aadcf8bd779fb6429692a86bf/src/package.json#L7-L11

我本地尝试 添加 --asar后，无法反编译，应该是路径的问题

因为 app.jsc 代码是加密的，没法继续排查

**Comment by ezshine** [comment]
更改了，新版仅保留了wxapkg的反编。去掉了直接转uniapp和taro，但是会跳转教程。还有asar也是压缩，如果每次启动都去解压asar也不太合适。
